version: '3.9'

services:
  influxdb:
    image: influxdb:2.1-alpine
    env_file:
      - influxv2.env
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdbv2:/var/lib/influxdb2:rw
    networks:
      - minha-rede
    ports:
      - "8086:8086"
  telegraf:
    image: telegraf:1.22-alpine
    depends_on:
      - influxdb
    volumes:
      - ./telegraf/mytelegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - influxv2.env
    networks:
      - minha-rede
  
  grafana:
    image: grafana/grafana-oss:latest
    restart: unless-stopped
    networks:
      - minha-rede
    ports:
      - "3000:3000"

  nginx:
    build:
        dockerfile: ./nginx/Dockerfile
        context: .
    image: nginx
    container_name: container-lb
    ports:
        - "80:80"
    networks: 
        - minha-rede
    depends_on:
        - "grafana"
        - "telegraf"
        - "influxdb"
        - "app"


  app:
    build: 
      context: ./Rick-Search-Engine
    image: rick
    networks: 
        - minha-rede

volumes:
  influxdbv2:

networks:
  minha-rede:
    driver: bridge